# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CalculatorService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CalculatorService.proto',
  package='CalculatorPackage',
  syntax='proto3',
  serialized_options=b'\n\tch.usi.saP\001',
  serialized_pb=b'\n\x17\x43\x61lculatorService.proto\x12\x11\x43\x61lculatorPackage\"\x1a\n\x08MyNumber\x12\x0e\n\x06number\x18\x01 \x01(\x05\"9\n\tMyNumbers\x12,\n\x07numbers\x18\x01 \x03(\x0b\x32\x1b.CalculatorPackage.MyNumber\"\t\n\x07Nothing2\xb8\x02\n\x11\x43\x61lculatorService\x12@\n\x03\x61\x64\x64\x12\x1c.CalculatorPackage.MyNumbers\x1a\x1b.CalculatorPackage.MyNumber\x12\x46\n\tfibonacci\x12\x1a.CalculatorPackage.Nothing\x1a\x1b.CalculatorPackage.MyNumber0\x01\x12\x46\n\x0cwaitSomeTime\x12\x1a.CalculatorPackage.Nothing\x1a\x1a.CalculatorPackage.Nothing\x12Q\n\x14\x66ibonacciServerCrash\x12\x1a.CalculatorPackage.Nothing\x1a\x1b.CalculatorPackage.MyNumber0\x01\x42\r\n\tch.usi.saP\x01\x62\x06proto3'
)




_MYNUMBER = _descriptor.Descriptor(
  name='MyNumber',
  full_name='CalculatorPackage.MyNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='CalculatorPackage.MyNumber.number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=72,
)


_MYNUMBERS = _descriptor.Descriptor(
  name='MyNumbers',
  full_name='CalculatorPackage.MyNumbers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='numbers', full_name='CalculatorPackage.MyNumbers.numbers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=131,
)


_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='CalculatorPackage.Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=142,
)

_MYNUMBERS.fields_by_name['numbers'].message_type = _MYNUMBER
DESCRIPTOR.message_types_by_name['MyNumber'] = _MYNUMBER
DESCRIPTOR.message_types_by_name['MyNumbers'] = _MYNUMBERS
DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyNumber = _reflection.GeneratedProtocolMessageType('MyNumber', (_message.Message,), {
  'DESCRIPTOR' : _MYNUMBER,
  '__module__' : 'CalculatorService_pb2'
  # @@protoc_insertion_point(class_scope:CalculatorPackage.MyNumber)
  })
_sym_db.RegisterMessage(MyNumber)

MyNumbers = _reflection.GeneratedProtocolMessageType('MyNumbers', (_message.Message,), {
  'DESCRIPTOR' : _MYNUMBERS,
  '__module__' : 'CalculatorService_pb2'
  # @@protoc_insertion_point(class_scope:CalculatorPackage.MyNumbers)
  })
_sym_db.RegisterMessage(MyNumbers)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), {
  'DESCRIPTOR' : _NOTHING,
  '__module__' : 'CalculatorService_pb2'
  # @@protoc_insertion_point(class_scope:CalculatorPackage.Nothing)
  })
_sym_db.RegisterMessage(Nothing)


DESCRIPTOR._options = None

_CALCULATORSERVICE = _descriptor.ServiceDescriptor(
  name='CalculatorService',
  full_name='CalculatorPackage.CalculatorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=145,
  serialized_end=457,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='CalculatorPackage.CalculatorService.add',
    index=0,
    containing_service=None,
    input_type=_MYNUMBERS,
    output_type=_MYNUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='fibonacci',
    full_name='CalculatorPackage.CalculatorService.fibonacci',
    index=1,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_MYNUMBER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='waitSomeTime',
    full_name='CalculatorPackage.CalculatorService.waitSomeTime',
    index=2,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_NOTHING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='fibonacciServerCrash',
    full_name='CalculatorPackage.CalculatorService.fibonacciServerCrash',
    index=3,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_MYNUMBER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATORSERVICE)

DESCRIPTOR.services_by_name['CalculatorService'] = _CALCULATORSERVICE

# @@protoc_insertion_point(module_scope)
